### ISSUE TITLE
Not running properly on Python 3.4.3

### ISSUE THREAD

**Issue by rishabh135** [csparpa/pyowm#100]
I tried using this api with python 3.4.3 , but I got following error message : 

   ```
 Traceback (most recent call last):
  File "C:/Python34/A pyton codes/openweather_api.py", line 9, in <module>
    forecast = owm.daily_forecast("Milan,it")
  File "C:\Python34\lib\site-packages\pyowm\webapi25\owm25.py", line 497, in daily_forecast
    forecast = self._parsers['forecast'].parse_JSON(json_data)
  File "C:\Python34\lib\site-packages\pyowm\webapi25\forecastparser.py", line 39, in parse_JSON
    d = json.loads(JSON_string)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
    
```

**Comment by csparpa** [comment]
Hi @rishabh135 as stated on the project manifest, Python 3.4+ is not yet officially supported.
Do you feel like submitting a patch for this specific issue?
Thanks

**Comment by csparpa** [comment]
@rishabh135 I tried to reproduce the issue running your exact command under Python3.4, but everything went smooth - I was able to correctly get the forecast

Maybe the bug had been caused by a temporary issue on the OWM API (things like that are quite common, unfortunately)

In any case, this PR #118 adds test coverage for Py34 and Py35

**Comment by rishabh135** [comment]
Well I hope so , its late here , but I will try it tomorrow to confirm , thanks a lot for the response.
