### ISSUE TITLE
weather_history_at_place() is broken

### ISSUE THREAD

**Issue by postables** [csparpa/pyowm#136]
When trying to run the command owm.weather_history_at_place() I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyowm-2.5.0-py3.4.egg/pyowm/commons/weather_client.py", line 58, in _lookup_cache_or_invoke_API
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pyowm-2.5.0-py3.4.egg/pyowm/webapi25/owm25.py", line 697, in weather_history_at_place
  File "/usr/local/lib/python3.4/dist-packages/pyowm-2.5.0-py3.4.egg/pyowm/commons/weather_client.py", line 91, in call_API
  File "/usr/local/lib/python3.4/dist-packages/pyowm-2.5.0-py3.4.egg/pyowm/commons/weather_client.py", line 61, in _lookup_cache_or_invoke_API

And according to the features list the weather_history() doesn't exist:
# **\* Historic hourly weather data recordings for a location ***
# http://api.openweathermap.org/data/2.5/history/city?q=London,uk
# search all recent weather history for London (last 24h approx)

list_of_weathers = owm.weather_history('London,uk')

**Comment by csparpa** [comment]
Hi @postables some OWM API features require a paid subscription tier.

The weather history is - in fact - a paid feature, as you can see [here](https://openweathermap.org/price). Can you confirm?

Action on my side: update [the outdated document](https://github.com/csparpa/pyowm/blob/master/docs/features.md) that you read.

Thanks!
