### ISSUE TITLE
NotFoundError Exception when using Tiles Client

### ISSUE THREAD

**Issue by sanmacorz** [csparpa/pyowm#401]
Hi! I have been trying to use the example from the Tiles client documentation on the official site, but I haven't been able to get it to run, it raises the exception NotFound when running the check_status_code function on the http_client file when trying to get the PNG file, but I'm not sure if I should somehow specify a URL target or something similar, any information would be appreciated, Thanks a lot!

This is the error I get:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 13, in <module>
    tile = tm.get_tile(5, 2, 6)
  File "/home/santiago/.local/lib/python3.10/site-packages/pyowm/tiles/tile_manager.py", line 50, in get_tile
    status, data = self.http_client.get_png(
  File "/home/santiago/.local/lib/python3.10/site-packages/pyowm/commons/http_client.py", line 189, in get_png
    HttpClient.check_status_code(resp.status_code, resp.text)
  File "/home/santiago/.local/lib/python3.10/site-packages/pyowm/commons/http_client.py", line 315, in check_status_code
    raise exceptions.NotFoundError('Unable to find the resource')
pyowm.commons.exceptions.NotFoundError: Unable to find the resource
```

From the code:

```
from pyowm import OWM
from pyowm.tiles.enums import MapLayerEnum

owm = OWM('my-API-key')

# Choose the map layer you want tiles for (eg. temeperature
layer_name = MapLayerEnum.TEMPERATURE

# Obtain an instance to a tile manager object
tm = owm.tile_manager(layer_name)

# Now say you want tile at coordinate x=5 y=2 at a zoom level of 6
tile = tm.get_tile(5, 2, 6)

# You can now save the tile to disk
tile.persist('/path/to/file.png')

# Wait! but now I need the pressure layer tile at the very same coordinates and zoom level! No worries...
# Just change the map layer name on the TileManager and off you go!
tm.map_layer = MapLayerEnum.PRESSURE
tile = tm.get_tile(5, 2, 6)
```

I'm running Python (3.10.4) - pyowm (3.3.0) on a 5.18.1 Arch Linux system

**Comment by csparpa** [comment]
@sanmacorz thanks for reporting this, this was due to a hack I've introduced a while ago to overcome bad design and lack of time. My bad... :-( but now this should be fixed.
