### ISSUE TITLE
if 'distance' in d['visibility']: TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by David-W98** [csparpa/pyowm#76]
My program was working yesterday, and as far as I remember nothing was changed since then. Now all of a sudden I'm getting the above error. Someone else had the same issue but closed the topic before getting a response.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "FSE code.py", line 65, in weatherwindow
    app.weather() # call weather function
  File "FSE code.py", line 46, in weather
    f = owm.weather_at_id(6182962) # pull forcast for Windsor Ontario
  File "build/bdist.linux-i686/egg/pyowm/webapi25/owm25.py", line 200, in weather_at_id
    return self._parsers['observation'].parse_JSON(json_data)
  File "build/bdist.linux-i686/egg/pyowm/webapi25/observationparser.py", line 60, in parse_JSON
    w = weather.weather_from_dictionary(d)
  File "build/bdist.linux-i686/egg/pyowm/webapi25/weather.py", line 430, in weather_from_dictionary
    if 'distance' in d['visibility']:
TypeError: argument of type 'int' is not iterable

**Comment by David-W98** [comment]
Just needed to update the library apparently, probably should've tried that first...

**Comment by csparpa** [comment]
Hi, yes that bug has been fixed last week with hotfix release 2.1.1
Anyway thanks for pointing this out!
